import { StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { fonts, fontSizes } from '../../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonLabel: {
    fontSize: 20,
    color: colors.ink,
  },
  headerTitle: {
    fontFamily: fonts.headingMedium,
    fontSize: fontSizes.title,
    color: colors.ink,
  },
  tabs: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  tabButton: {
    flex: 1,
    backgroundColor: colors.card,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  tabButtonLabel: {
    fontFamily: fonts.headingMedium,
    fontSize: fontSizes.bodySmall,
    color: colors.muted,
  },
  tabButtonLabelActive: {
    color: '#fff',
  },
  body: {
    padding: 18,
    paddingBottom: 40,
  },
  sectionLabel: {
    fontFamily: fonts.headingBold,
    fontSize: fontSizes.label,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: colors.muted,
    marginBottom: 14,
  },
  hintText: {
    fontFamily: fonts.body,
    fontSize: fontSizes.bodySmall,
    color: colors.muted,
    lineHeight: 20,
    marginBottom: 12,
    marginTop: -6,
  },
  sosAlertBlock: {
    borderColor: colors.danger,
    borderWidth: 2,
  },
  sosAlertMeta: {
    fontFamily: fonts.body,
    fontSize: fontSizes.bodySmall,
    color: colors.ink,
    marginBottom: 8,
  },
  sosAlertLink: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.primaryDark,
    lineHeight: 20,
  },
  block: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
  },
  blockTitle: {
    fontFamily: fonts.headingMedium,
    fontSize: 17,
    color: colors.ink,
    marginBottom: 12,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  itemEmoji: {
    fontSize: 22,
  },
  itemName: {
    flex: 1,
    fontFamily: fonts.body,
    fontSize: fontSizes.body,
    color: colors.ink,
  },
  photoButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoButtonLabel: {
    fontSize: 15,
  },
  deleteLabel: {
    fontSize: 18,
    color: colors.muted,
    paddingHorizontal: 6,
  },
  emptyLabel: {
    fontFamily: fonts.body,
    fontSize: fontSizes.bodySmall,
    color: colors.muted,
    paddingVertical: 6,
  },
  errorText: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.danger,
    marginTop: 6,
  },
  contactInfo: {
    flex: 1,
  },
  contactRelation: {
    fontFamily: fonts.body,
    fontWeight: '400',
    color: colors.muted,
  },
  contactPhone: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.muted,
  },
  contactFormRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  contactPhoneInput: {
    marginTop: 10,
  },
  addContactButton: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  emojiRow: {
    marginTop: 12,
  },
  emojiChoice: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  emojiChoiceSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.categories.need.background,
  },
  emojiChoiceLabel: {
    fontSize: 18,
  },
  addRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  input: {
    flex: 1,
    fontFamily: fonts.body,
    fontSize: fontSizes.bodySmall,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.ink,
  },
  addButton: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  addButtonLabel: {
    fontFamily: fonts.headingMedium,
    fontSize: fontSizes.bodySmall,
    color: '#fff',
  },
  signOutButton: {
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 8,
  },
  signOutLabel: {
    fontFamily: fonts.body,
    fontSize: fontSizes.body,
    color: colors.danger,
    textDecorationLine: 'underline',
  },
  statRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 16,
    alignItems: 'center',
  },
  statNum: {
    fontFamily: fonts.headingBold,
    fontSize: 28,
    color: colors.primaryDark,
  },
  statLabel: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.muted,
    marginTop: 2,
    textAlign: 'center',
  },
  barRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  barDay: {
    width: 34,
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.muted,
  },
  barTrack: {
    flex: 1,
    backgroundColor: colors.background,
    borderRadius: 8,
    height: 16,
    overflow: 'hidden',
  },
  barFill: {
    backgroundColor: colors.primary,
    height: '100%',
    borderRadius: 8,
  },
  barCount: {
    width: 20,
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.muted,
    textAlign: 'right',
  },
  reportText: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.ink,
    lineHeight: 21,
    backgroundColor: colors.background,
    borderRadius: 12,
    padding: 12,
  },
  recentList: {
    marginTop: 14,
  },
  recentItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  recentItemLabel: {
    fontFamily: fonts.body,
    fontSize: fontSizes.bodySmall,
    color: colors.ink,
  },
  recentItemDate: {
    fontFamily: fonts.body,
    fontSize: fontSizes.bodySmall,
    color: colors.muted,
  },
  fontScaleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  fontScaleButton: {
    flex: 1,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  fontScaleButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  fontScaleButtonLabel: {
    fontFamily: fonts.headingMedium,
    fontSize: fontSizes.bodySmall,
    color: colors.ink,
  },
  fontScaleButtonLabelActive: {
    color: '#fff',
  },
  switchScanningTitle: {
    fontFamily: fonts.headingMedium,
    fontSize: 15,
    color: colors.ink,
    marginTop: 16,
    marginBottom: 4,
  },
  switchScanningDescription: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.muted,
    lineHeight: 19,
    marginBottom: 10,
  },
});
